force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CourseController.cls
public with sharing class CourseController {
	@AuraEnabled
	public static List<Models.Course> getStudentCourses() {
		try {
			List<Models.Course> courses = new List<Models.Course>();
			for (Course__c course : DataProvider.getStudentCourses()) {
				Models.Course courseModel = new Models.Course();
				courseModel.id = course.Id;
				courseModel.link = '/course/' + course.Id;
				courseModel.name = course.Name;
				courseModel.credits = course.Credits__c;
				courses.add(courseModel);
			}
			return courses;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}