force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <label>Lecture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecture__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Group__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FileControllerTest.cls
@IsTest
public class FileControllerTest {
    @isTest
	public static void should_createContentDistributions() {
		User teacher = TestUtil.buildPortalTeacherUser();
		Course__c course = (Course__c) TestUtil.createRecord('Course__c', new Map<String, Object> {
			'Name' => TestUtil.getRandomString(5),
			'Credits__c' => 5
		});
		Lecture__c lecture = (Lecture__c) TestUtil.createRecord('Lecture__c', new Map<String, Object> {
			'Name' => 'Lecture 1',
			'Course__c' => course.Id,
			'Teacher__c' => teacher.ContactId,
			'StartTime__c' => datetime.now(),
			'EndTime__c' => datetime.now().addHours(1)
		});

		ContentVersion content = new ContentVersion(); 
		content.Title = 'PPM'; 
		content.PathOnClient = '/' + content.Title + '.jpg';
		content.VersionData = Blob.valueOf('Unit Test ContentVersion Body'); 
		content.origin = 'H';
		insert content;
		ContentDocumentLink contentlink = new ContentDocumentLink();
		contentlink.LinkedEntityId = lecture.Id;
		contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :content.Id].ContentDocumentId;
		contentlink.ShareType = 'V';
		contentlink.Visibility = 'AllUsers'; 
		insert contentlink;

		Test.startTest();
		FileController.createContentDistributions(new List<Id>{contentLink.ContentDocumentId}, contentlink.LinkedEntityId);
		List<Models.File> files = FileController.getFiles(lecture.Id);
        Test.stopTest();

		Assert.areEqual(1, files.size());
	}

    @isTest
	public static void should_deleteFile() {
        User teacher = TestUtil.buildPortalTeacherUser();
		Course__c course = (Course__c) TestUtil.createRecord('Course__c', new Map<String, Object> {
			'Name' => TestUtil.getRandomString(5),
			'Credits__c' => 5
		});
		Lecture__c lecture = (Lecture__c) TestUtil.createRecord('Lecture__c', new Map<String, Object> {
			'Name' => 'Lecture 1',
			'Course__c' => course.Id,
			'Teacher__c' => teacher.ContactId,
			'StartTime__c' => datetime.now(),
			'EndTime__c' => datetime.now().addHours(1)
		});

		ContentVersion content = new ContentVersion(); 
		content.Title = 'PPM'; 
		content.PathOnClient = '/' + content.Title + '.jpg';
		content.VersionData = Blob.valueOf('Unit Test ContentVersion Body'); 
		content.origin = 'H';
		insert content;
		ContentDocumentLink contentlink = new ContentDocumentLink();
		contentlink.LinkedEntityId = lecture.Id;
		contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :content.Id].ContentDocumentId;
		contentlink.ShareType = 'V';
		contentlink.Visibility = 'AllUsers'; 
		insert contentlink;

		Test.startTest();
		FileController.createContentDistributions(new List<Id>{contentLink.ContentDocumentId}, contentlink.LinkedEntityId);
		FileController.deleteFile(contentLink.ContentDocumentId);
        List<Models.File> files = FileController.getFiles(lecture.Id);
        Test.stopTest();

		Assert.areEqual(0, files.size());
    }
}