force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Course__c/Group_Course__c.object-meta.xml
<CustomObject>
    <label>Group Course</label>
    <nameField>
        <displayFormat>GC-{0000}</displayFormat>
        <label>Group Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Group_Course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Group Courses</relationshipLabel>
    <relationshipName>Group_Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group_Course__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Group Courses</relationshipLabel>
    <relationshipName>Group_Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <label>Lecture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecture__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Group__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DocumentUtilTest.cls
@isTest
public class DocumentUtilTest {
	@isTest
	public static void should_checkIsLinked(){
		Group__c group1 = (Group__c) TestUtil.createRecord('Group__c', new Map<String, Object>{
			'Name' => TestUtil.getRandomString(5)
		});
		User student = TestUtil.buildPortalStudentUser(group1.Id);
		User teacher = TestUtil.buildPortalTeacherUser();
		Course__c course = (Course__c) TestUtil.createRecord('Course__c', new Map<String, Object> {
			'Name' => TestUtil.getRandomString(5),
			'Credits__c' => 5
		});
		Group_Course__c groupCourse = (Group_Course__c) TestUtil.createRecord('Group_Course__c', new Map<String, Object> {
			'Group__c' => group1.Id,
			'Course__c' => course.Id
		});
		Lecture__c lecture = (Lecture__c) TestUtil.createRecord('Lecture__c', new Map<String, Object> {
			'Name' => 'Lecture 1',
			'Course__c' => course.Id,
			'Teacher__c' => teacher.ContactId,
			'StartTime__c' => datetime.now(),
			'EndTime__c' => datetime.now().addHours(1)
		});

		ContentVersion content = new ContentVersion(); 
		content.Title = 'PPM'; 
		content.PathOnClient = '/' + content.Title + '.jpg';
		content.VersionData = Blob.valueOf('Unit Test ContentVersion Body'); 
		content.origin = 'H';
		insert content;
		ContentDocumentLink contentlink = new ContentDocumentLink();
		contentlink.LinkedEntityId = lecture.Id;
		contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :content.Id].ContentDocumentId;
		contentlink.ShareType = 'V';
		contentlink.Visibility = 'AllUsers'; 
		insert contentlink;

		Test.startTest();
		Assert.isTrue(DocumentUtil.isLinked(contentLink, 'Lecture__c'));
		Test.stopTest();
	}

	@isTest
	public static void should_createContentDistributions(){
		Group__c group1 = (Group__c) TestUtil.createRecord('Group__c', new Map<String, Object>{
			'Name' => TestUtil.getRandomString(5)
		});
		User student = TestUtil.buildPortalStudentUser(group1.Id);
		User teacher = TestUtil.buildPortalTeacherUser();
		Course__c course = (Course__c) TestUtil.createRecord('Course__c', new Map<String, Object> {
			'Name' => TestUtil.getRandomString(5),
			'Credits__c' => 5
		});
		Group_Course__c groupCourse = (Group_Course__c) TestUtil.createRecord('Group_Course__c', new Map<String, Object> {
			'Group__c' => group1.Id,
			'Course__c' => course.Id
		});
		Lecture__c lecture = (Lecture__c) TestUtil.createRecord('Lecture__c', new Map<String, Object> {
			'Name' => 'Lecture 1',
			'Course__c' => course.Id,
			'Teacher__c' => teacher.ContactId,
			'StartTime__c' => datetime.now(),
			'EndTime__c' => datetime.now().addHours(1)
		});

		ContentVersion content = new ContentVersion(); 
		content.Title = 'PPM'; 
		content.PathOnClient = '/' + content.Title + '.jpg';
		content.VersionData = Blob.valueOf('Unit Test ContentVersion Body'); 
		content.origin = 'H';
		insert content;
		ContentDocumentLink contentlink = new ContentDocumentLink();
		contentlink.LinkedEntityId = lecture.Id;
		contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :content.Id].ContentDocumentId;
		contentlink.ShareType = 'V';
		contentlink.Visibility = 'AllUsers'; 
		insert contentlink;

		Test.startTest();
		DocumentUtil.createContentDistributions(new List<Id>{contentLink.ContentDocumentId}, contentlink.LinkedEntityId);
		Test.stopTest();

		List<ContentDistribution> result = [SELECT Id FROM ContentDistribution];
		Assert.areEqual(1, result.size());
	}

}