force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/ConferenceLink__c.field-meta.xml
<CustomField>
    <fullName>ConferenceLink__c</fullName>
    <label>Conference Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/Lecture__c.object-meta.xml
<CustomObject>
    <label>Lecture</label>
    <nameField>
        <label>Lecture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lectures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Lecture__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lecture__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Group__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lectures</relationshipLabel>
    <relationshipName>Lectures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>Task-{0000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ScheduleController.cls
public with sharing class ScheduleController {
	@AuraEnabled
	public static List<Models.Event> getScheduleData(String audience) {
		try {
			List<Models.Event> data = new List<Models.Event>();
			List<Course__c> courses = new List<Course__c>();
			if (audience == 'Teacher') {
				courses = DataProvider.getAllCourses();
			} else {
				courses = DataProvider.getStudentCourses();
			}
			for (Course__c course : courses) {
				for (Lecture__c lecture : course.Lectures__r) {
					Models.Event event = new Models.Event();
					event.id = lecture.Id;
					event.name = lecture.Name;
					event.link = lecture.ConferenceLink__c;
					event.startTime = lecture.StartTime__c?.addHours(1);
					event.endTime = lecture.EndTime__c?.addHours(1);
					event.teacherName = lecture.Teacher__r.Name;
					event.teacherId = lecture.Teacher__c;
					event.type = 'Lecture';
					data.add(event);
				}
				for (Assignment__c assignment : course.Assignments__r) {
					Models.Event event = new Models.Event();
					event.id = assignment.Id;
					event.name = assignment.Name;
					event.link = assignment.ConferenceLink__c;
					event.startTime = assignment.StartTime__c?.addHours(1);
					event.endTime = assignment.EndTime__c?.addHours(1);
					event.teacherName = assignment.Teacher__r.Name;
					event.teacherId = assignment.Teacher__c;
					event.type = SchemaUtils.getRecordTypeName('Assignment__c', assignment.RecordTypeId);
					data.add(event);
				}
			}
			return data;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}